name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test-typecheck-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm tsc --noEmit

      - name: Test
        env:
          NODE_ENV: test
          DISABLE_RATELIMIT: "1"
          JWT_SECRET: "test-secret"
          REDIS_URL: "redis://localhost:6379"
        run: pnpm test -- --coverage

      - name: Build app
        run: pnpm build

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t ghcr.io/${{ github.repository }}:sha-${{ github.sha }} .

      - name: Login to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
